env : dev

#===============角色设定===============================
context_manager:
  role: "你的名字是小镜/小朋友，你是一款知书达理的多语言汉学互联镜，你能够说中英日三国语言，集成摄像头、麦克风等外设，擅长引经据典。你说话很简洁精准，不失幽默。请多用口语，不用md格式。"
wakeup_words : ["你好", "树莓派", "小", "小朋友", "朋友","小镜子"]
#===============选择接口===============================
choose:
  tts: tts_huoshan
  asr: asr_paraformer
  llm: "qwen"
#===============参数调节===============================
time:
  timeout: 30
#===============api接口配置============================
asr :
    asr_baidu:
      baidu_app_id: "117625416"
      baidu_api_key: "sbxqfkRAM3Xf0ryTRPNpDFqJ"
      baidu_secret_key: "ppdTdrkTqan7IDWUQhIDhBLEmR4k9SZn"
    asr_paraformer:
      dashscope.api_key: "sk-acccd325f0f7452b935947606d5b565a"
      # ['zh','en','ja','fr','ru','yue','ko','de'] 中文是：zh_cn, 英语是：en_us, 日语是：ja_jp, 法语是：fr_fr, 俄语是：ru
      language_hints : ['zh','en','ja']
      model: "paraformer-realtime-v2"

tts :
  tts_aliyun:

  tts_huoshan :
    appid: 6082784057
    token: bF4nRpNiCcP8HDLfDJYvFupObvZxy0gq
    cluster: volcano_tts
    # zh_male_yuanboxiaoshu_moon_bigtts 渊博小叔
    # zh_female_shuangkuaisisi_moon_bigtts 中英
    # zh_male_jingqiangkanye_emo_mars_bigtts 京腔侃爷
    # zh_female_yingyujiaoyu_mars_bigtts tina老师
    # ICL_zh_female_chengshujiejie_tob 成熟姐姐
    # zh_male_tiancaitongsheng_mars_bigtts天才童声
    # BV700_streaming 普通
    voice_type:
      default: "zh_male_tiancaitongsheng_mars_bigtts"
      ja: "multi_female_shuangkuaisisi_moon_bigtts"
      de: "zh_male_tiancaitongsheng_mars_bigtts"
      fr: "zh_male_tiancaitongsheng_mars_bigtts"
    #中文音色：开心（happy），悲伤（sad），生气（angry），惊讶（surprised），恐惧（fear），厌恶（hate），激动（excited），冷漠（coldness），中性（neutral），沮丧（depressed），撒娇（lovey-dovey），害羞（shy），安慰鼓励（comfort），咆哮/焦急（tension），温柔（tender），讲故事 / 自然讲述（storytelling），情感电台（radio），磁性（magnetic），广告营销（advertising），气泡音（vocal - fry），低语 (ASMR)，新闻播报（news），娱乐八卦（entertainment），方言（dialect）
    #英文音色：中性（neutral），愉悦（happy），愤怒（angry），悲伤（sad），兴奋（excited），对话 / 闲聊（chat），低语 (ASMR)，温暖（warm），深情（affectionate），权威（authoritative）
    motion_type: "happy"
    host: openspeech.bytedance.com
    # 单向 "wss://openspeech.bytedance.com/api/v1/tts/ws_binary"
    # 双向(暂不支持) "wss://openspeech.bytedance.com/api/v3/tts/bidirection"
    url: "wss://openspeech.bytedance.com/api/v1/tts/ws_binary"
    # 多情感甜心小美 zh_female_tianxinxiaomei_emo_v2_mars_bigtts
    voice_type_fast: "zh_female_tianxinxiaomei_emo_v2_mars_bigtts"
  tts_baidu:
    baidu_app_id: "117625416"
    baidu_api_key: "sbxqfkRAM3Xf0ryTRPNpDFqJ"
    baidu_secret_key: "ppdTdrkTqan7IDWUQhIDhBLEmR4k9SZn"

llm :
  deepseek:
    deepseek_api_key: sk-c845c48b0588407cafad226db8882bba
    deepseek_api_url: https://api.deepseek.com/v1/chat/completions
  qwen:
    qwen_api_key: "sk-acccd325f0f7452b935947606d5b565a"
    model: "qwen-turbo"

weather :
  weather_api_key: "8ff8d7c3dd9d4e3190df3931536544ef"

iot :
  tuya_api_id: ""
  tuya_api_secret : ""
